{
  boolean wasThrown=false;
  try {
    exceptionCase.tryClosure();
  }
 catch (  Throwable var9) {
    if (shouldOccur) {
      wasThrown=true;
      String errorMessage=exceptionCase.getAssertionErrorMessage();
      assertEquals(errorMessage,exceptionCase.getExpectedExceptionClass(),var9.getClass());
      if (expectedErrorMsg != null) {
        assertEquals("Compare error messages",expectedErrorMsg,var9.getMessage());
      }
    }
 else {
      if (!exceptionCase.getExpectedExceptionClass().equals(var9.getClass())) {
        throw var9;
      }
      wasThrown=true;
      System.out.println("");
      var9.printStackTrace(System.out);
      fail("Exception isn\'t expected here. Exception message: " + var9.getMessage());
    }
  }
 finally {
    if (shouldOccur && !wasThrown) {
      fail(exceptionCase.getAssertionErrorMessage());
    }
  }
}
