{
  handleJumpInsideTryFinally(error);
  add(new ThrowExceptionInstruction(expression,error));
}
